[phases.setup]
nixPkgs = ["ffmpeg", "python311", "pa", "gobject-introspection", "glib"]

[phases.install]
cmds = ["pip install -r requirements.txt"]
[phases.setup]
nixPkgs = ["ffmpeg", "python311", "pa", "gobject-introspection", "glib", "cairo", "pango", "gtk3"]
